### ISSUE TITLE
List Filters

### ISSUE THREAD

**Issue by gtjamesa** [gtjamesa/ge-tracker-app#71]
**Is your feature request related to a problem? Please describe.**
Related to #30 and #79 

**Describe the solution you'd like**
There should either be a filters button or tab that the user can use to configure filters for the item list. If the list is one of the main lists (that have filters on Desktop), then these filters should be synced to Desktop.

There should be an option to create "mobile only" filters instead of saving the changes to the Desktop version

## To-do

- [x] Convert all lists to apply default filters
- [x] Create interface to update filters
- [x] Apply sorting on `profit` field to the list by default
- [x] Create interface to edit sorting rules
- [x] Update API endpoints to *not* include filters by default
- [x] Update `ge-tracker-api` package to control whether or not to include filters
- [x] Create global interface to control filters (just F2P only?)

### Lists to be converted:
- [x] Default lists (HM, Favourites, etc.)
- [x] High alchemy
- [x] Decant potions
- [x] Herblore profit (make potions, clean herbs, unfinished potions)
- [x] Item sets
- [x] Barrows repair
- [x] Magic tablets
- [x] Plank making
- [x] Tan leather
- [x] Store profit

### API Endpoints to be checked:
- [x] Favourite items
- [x] Suggested items
- [x] Highest margins
- [x] High volume
- [x] GE limits
- [x] New items
- [x] High alchemy
- [x] Decant potions
- [ ] Make potions
- [ ] Clean herbs
- [ ] Unfinished potions
- [x] Item sets
- [ ] Barrows repair
- [ ] Magic tablets
- [ ] Plank making
- [ ] Tan leather
- [ ] Store profit
